spring.application.name=comment-service
server.port=8130

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

eureka.client.service-url.defaultZone=${EUREKA_URL}
eureka.instance.prefer-ip-address=false
eureka.instance.hostname=localhost

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}


# Feign
spring.cloud.openfeign.client.config.auth-service.url=http://localhost:8080
spring.cloud.openfeign.client.config.card-service.url=http://localhost:8120

cloudinary.cloud-name=YOUR_CLOUD_NAME
cloudinary.api-key=YOUR_API_KEY
cloudinary.api-secret=YOUR_API_SECRET
