spring.application.name=api-gateway
server.port=8765


# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka


# Spring Security
spring.security.user.name=disabled
spring.security.user.password=disabled

# Swagger UI at http://localhost:8765/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html


springdoc.swagger-ui.urls[0].name=Auth Service
springdoc.swagger-ui.urls[0].url=/auth-service/v3/api-docs

springdoc.swagger-ui.urls[1].name=Workspace Service
springdoc.swagger-ui.urls[1].url=/workspace-service/v3/api-docs

springdoc.swagger-ui.urls[2].name=Board Service
springdoc.swagger-ui.urls[2].url=/board-service/v3/api-docs

springdoc.swagger-ui.urls[3].name=List Service
springdoc.swagger-ui.urls[3].url=/list-service/v3/api-docs

springdoc.swagger-ui.urls[4].name=Card Service
springdoc.swagger-ui.urls[4].url=/card-service/v3/api-docs

springdoc.swagger-ui.urls[5].name=Comment Service
springdoc.swagger-ui.urls[5].url=/comment-service/v3/api-docs

springdoc.swagger-ui.urls[6].name=Label Service
springdoc.swagger-ui.urls[6].url=/label-service/v3/api-docs

springdoc.swagger-ui.urls[7].name=Notification Service
springdoc.swagger-ui.urls[7].url=/notification-service/v3/api-docs
