spring.application.name=api-gateway
server.port=8765


# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka


# Spring Security
spring.security.user.name=disabled
spring.security.user.password=disabled

